# This is a basic workflow to help you get started with Actions

name: Deploy AWS Amplify

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [master]
    pull_request:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            # Runs a single command using the runners shell
            - name: Install
              run: npm ci

            # Runs a set of commands using the runners shell
            - name: Build
              run: npm run prod
    deploy:
        needs: build
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: eu-west-1
            AWS_DEFAULT_OUTPUT: json
        steps:
            - uses: actions/checkout/@v2
            - name: Deploy
              run: |
                  JOB_ID=$(aws amplify start-job --app-id d1v8vc4zl1pbl8 --branch-name master --job-type RELEASE | jq -r '.jobSummary.jobId')
                  JOB_STATUS="$(aws amplify get-job --app-id d1v8vc4zl1pbl8 --branch-name master --job-id $JOB_ID | jq -r '.job.summary.status')"
                  while [[ "$JOB_STATUS" =~ ^(PENDING|RUNNING)$ ]]; do sleep 1; JOB_STATUS="$(aws amplify get-job --app-id d1v8vc4zl1pbl8 --branch-name master --job-id $JOB_ID | jq -r '.job.summary.status')"; echo "$JOB_STATUS"; done
                  echo "Job status is $JOB_STATUS"
                  echo "Job finished"
