name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: npm ci
      
      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
